### ISSUE TITLE
Look into current state styling on sidenav

### ISSUE THREAD

**Issue by cmajel** [18F/content-guide-uswds#6]
Currently looks like this:
![Screen Shot 2020-03-13 at 3 27 32 PM](https://user-images.githubusercontent.com/2374206/76653567-4a2c8c80-653f-11ea-914b-4a22a8c2b161.png)

Goal is to have a highlight bar like this:
![Screen Shot 2020-03-13 at 3 28 36 PM](https://user-images.githubusercontent.com/2374206/76653586-557fb800-653f-11ea-91a4-8d6f4d289c1a.png)

From our conversation, we want to explore:
* Collapsable sections
* An active state for the parent category
* If sub page, a differently styled active state is shown

**Comment by brentryanjohnson** [comment]
Moved sidenav to UX Guide port. Closing.
