### ISSUE TITLE
Link color is set at default rather than theme color

### ISSUE THREAD

**Issue by cmajel** [18F/content-guide-uswds#7]
Currently looks like this:

![Screen Shot 2020-03-13 at 3 30 14 PM](https://user-images.githubusercontent.com/2374206/76653789-cde67900-653f-11ea-8615-8a1a2283d39f.png)

Where, we'd expect it to be pulling in the theme's link color

**Comment by brentryanjohnson** [comment]
Resolved with UX guide port
